// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efcoretest;

#nullable disable

namespace efcoretest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220316110533_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("efcoretest.Model.Hour", b =>
                {
                    b.Property<int>("Hour_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hour_Id");

                    b.ToTable("Hours");
                });

            modelBuilder.Entity("efcoretest.Model.Minute", b =>
                {
                    b.Property<int>("Minute_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Minute_Id");

                    b.HasIndex(new[] { "Name" }, "IX_Name_Unique")
                        .IsUnique();

                    b.ToTable("Minutes");
                });
#pragma warning restore 612, 618
        }
    }
}
